name: shelf_master
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  camera: ^0.10.5
  collection: ^1.17.0
  easy_image_viewer: ^1.2.0
  firebase_analytics: ^10.3.0
  firebase_core: ^2.9.0
  firebase_core_platform_interface: ^4.6.0
  firebase_crashlytics: ^3.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_flavor: ^3.1.1
  flutter_localizations:
    sdk: flutter
  flutter_slidable: ^3.0.0
  flutter_svg: ^1.1.6
  freezed_annotation: ^2.2.0
  go_router: ^7.0.0
  image: ^4.0.16
  json_annotation: ^4.8.1
  native_device_orientation: ^1.1.4
  path: ^1.8.2
  path_provider: ^2.0.14
  pdf: ^3.10.1
  printing: ^5.10.3
  qr_code_scanner: ^1.0.1
  realm: ^1.0.3
  speech_to_text: ^6.1.1

dev_dependencies:
  build_runner: ^2.3.3
  build_verify: ^3.1.0
  dart_code_metrics: ^5.7.2
  flutter_launcher_icons: ^0.12.0
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.2.19
  flutter_test:
    sdk: flutter
  freezed: ^2.3.3
  go_router_builder: ^2.0.0
  golden_toolkit: ^0.13.0
  mocktail: ^0.3.0
  recase: ^4.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/font/ubuntu_bold.ttf
        - asset: assets/font/ubuntu_medium.ttf
        - asset: assets/font/ubuntu_regular.ttf
        - asset: assets/font/ubuntu_light.ttf